SELECT AUTHORS.AU_ID AS 'AUTHORS ID',
AUTHORS.AU_LNAME AS 'AUTHORS LAST NAME',
AUTHORS.AU_FNAME AS 'AUTHORS FIRST NAME',
TITLES.TITLE AS 'TITLE',
PUBLISHERS.PUB_NAME AS 'PUBLISHER'

FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN PUBLISHERS ON PUBLISHERS.PUB_ID = TITLES.PUB_ID
;

SELECT AUTHORS.AU_ID AS 'AUTHORS ID',
AUTHORS.AU_LNAME AS 'AUTHORS LAST NAME',
AUTHORS.AU_FNAME AS 'AUTHORS FIRST NAME',
PUBLISHERS.PUB_NAME AS 'PUBLISHER',
COUNT(TITLEAUTHOR.TITLE_ID) AS 'TITLE COUNT'

FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN PUBLISHERS ON PUBLISHERS.PUB_ID = TITLES.PUB_ID


GROUP BY AUTHORS.AU_ID,AUTHORS.AU_LNAME,AUTHORS.AU_FNAME,PUBLISHERS.PUB_NAME
;

SELECT AUTHORS.AU_ID AS 'AUTHORS ID',
AUTHORS.AU_LNAME AS 'AUTHORS LAST NAME',
AUTHORS.AU_FNAME AS 'AUTHORS FIRST NAME',
PUBLISHERS.PUB_NAME AS 'PUBLISHER',
COUNT(TITLEAUTHOR.TITLE_ID) AS 'TITLE COUNT',
SUM(SALES.QTY) AS 'TOTAL'


FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN PUBLISHERS ON PUBLISHERS.PUB_ID = TITLES.PUB_ID
LEFT JOIN SALES ON SALES.TITLE_ID = TITLES.TITLE_ID


GROUP BY AUTHORS.AU_ID,AUTHORS.AU_LNAME,AUTHORS.AU_FNAME,PUBLISHERS.PUB_NAME
ORDER BY SUM(SALES.QTY) DESC
LIMIT 3
;

SELECT AUTHORS.AU_ID AS 'AUTHORS ID',
AUTHORS.AU_LNAME AS 'AUTHORS LAST NAME',
AUTHORS.AU_FNAME AS 'AUTHORS FIRST NAME',
PUBLISHERS.PUB_NAME AS 'PUBLISHER',
COUNT(TITLEAUTHOR.TITLE_ID) AS 'TITLE COUNT',
SUM(SALES.QTY) AS 'TOTAL'


FROM AUTHORS

LEFT JOIN TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
LEFT JOIN TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
LEFT JOIN PUBLISHERS ON PUBLISHERS.PUB_ID = TITLES.PUB_ID
LEFT JOIN SALES ON SALES.TITLE_ID = TITLES.TITLE_ID


GROUP BY AUTHORS.AU_ID,AUTHORS.AU_LNAME,AUTHORS.AU_FNAME,PUBLISHERS.PUB_NAME
ORDER BY SUM(SALES.QTY) DESC
LIMIT 23
;

